language: csharp
env:
  global:
    - SOLUTION_PATH=$TRAVIS_BUILD_DIR + /AbstractionLib.sln
    - ARTIFACT_STORAGE=$TRAVIS_BUILD_DIR + /artifacts
solution: ../AbstractionLib/AbstractionLib.sln

jobs:
  include:
    - dotnet: latest

install:
  - mkdir $ARTIFACT_STORAGE
  - cd $TRAVIS_BUILD_DIR + /AbstractionLib/; dotnet restore
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory $ARTIFACT_STORAGE + testrunner
# Utworzyć skrypt który jedzie po wszystkich rozwiązaniach i je pakuje wraz z odpowiednią wersją
build:
  - dotnet pack -o ./Builds -c Release